"""Scaffold a new AgentDraft project (3.5.2): a working schema.yaml plus its
supporting Python module(s), a NOTES.md for the bundled search_docs tool to
find, and a .env.example - so `pip install agentdraft` followed by
`agentdraft init` gets a new user to a runnable agent immediately.
"""

from pathlib import Path

_NOTES_MD = """# Notes

This is a starter file for your agent's `search_docs` tool to search. Replace
it with your own project's documentation - anything in this directory's
`*.md` files is fair game.
"""

_TOOLS_PY = '''"""Example tool generated by `agentdraft init`: searches this project's own
*.md files. Replace with your own tools once you're ready.
"""

from pathlib import Path

from langchain_core.tools import tool

_SEARCH_DIR = Path(__file__).resolve().parent


@tool
def search_docs(query: str) -> str:
    """Search this project's *.md files for lines mentioning `query`, case-insensitively."""
    query_lower = query.lower()
    matches: list[str] = []
    for doc_path in sorted(_SEARCH_DIR.rglob("*.md")):
        for line_number, line in enumerate(doc_path.read_text().splitlines(), start=1):
            if query_lower in line.lower():
                matches.append(f"{doc_path.name}:{line_number}: {line.strip()}")
    if not matches:
        return "No matching lines found."
    return "\\n".join(matches[:10])
'''

_ANTHROPIC_SCHEMA_YAML = """# Generated by `agentdraft init`. Edit freely - now your project.
#
# A single tool-calling node that answers questions using search_docs, which
# searches this directory's own *.md files (see NOTES.md).
#
# Needs a real ANTHROPIC_API_KEY - see .env.example.
schema_version: 1
nodes:
  - id: assistant
    llm:
      provider: anthropic
      model: claude-sonnet-5
      system: >
        You are a helpful assistant. Call search_docs to find relevant
        information before answering, and say you don't know if nothing
        relevant turns up rather than guessing.
    tools:
      - tools:search_docs
"""

_OPENAI_SCHEMA_YAML = """# Generated by `agentdraft init`. Edit freely - this is your project now.
#
# A router node picks between a docs-search node (search_docs, this
# directory's own *.md files - see NOTES.md) and a zero-cost greeting
# handler for small talk.
#
# Needs a real OPENAI_API_KEY - see .env.example.
schema_version: 1
nodes:
  - id: router
    llm:
      provider: openai
      model: gpt-4o-mini
      system: >
        Classify the user's message. Reply with exactly one word: "docs" if
        they're asking a question about this project or its docs, or "chat"
        if it's just a greeting or small talk. No other text.
  - id: search
    llm:
      provider: openai
      model: gpt-4o-mini
      system: >
        You are a helpful assistant. Call search_docs to find relevant
        information before answering, and say you don't know if nothing
        relevant turns up rather than guessing.
    tools:
      - tools:search_docs
  - id: greet
    handler: handlers:friendly_greeting
edges:
  - from: START
    to: router
  - from: router
    condition: routing:by_router_verdict
    routes:
      docs: search
      chat: greet
  - from: search
    to: END
  - from: greet
    to: END
"""

_HANDLERS_PY = '''"""Example custom-code node handler generated by `agentdraft init`."""

from typing import Any

from langchain_core.messages import AIMessage


def friendly_greeting(state: dict[str, Any]) -> dict[str, Any]:
    """Zero-cost reply for small talk - no docs search or LLM call needed."""
    return {"messages": [AIMessage(content="Hey! Ask me anything about this project's docs.")]}
'''

_ROUTING_PY = '''"""Example conditional-edge routing function generated by `agentdraft init`."""

from typing import Any


def by_router_verdict(state: dict[str, Any]) -> str:
    """Read the router node's one-word verdict ("docs" or "chat")."""
    verdict = state["messages"][-1].content.strip().lower()
    return "docs" if "docs" in verdict else "chat"
'''

PROVIDERS = ("anthropic", "openai")

#: Env var `agentdraft doctor` (3.5.3) also uses to check a schema's provider
#: against the environment - kept here since `init` owns the provider->key
#: association for the templates it generates.
PROVIDER_API_KEY_ENV = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
}


class ScaffoldExistsError(Exception):
    """Raised when scaffold's target files already exist and force wasn't given."""

    def __init__(self, existing: list[str]) -> None:
        self.existing = existing
        super().__init__(f"file(s) already exist: {', '.join(existing)}")


def _files_for(provider: str) -> dict[str, str]:
    env_example = f"{PROVIDER_API_KEY_ENV[provider]}=\n"
    if provider == "anthropic":
        return {
            "schema.yaml": _ANTHROPIC_SCHEMA_YAML,
            "tools.py": _TOOLS_PY,
            "NOTES.md": _NOTES_MD,
            ".env.example": env_example,
        }
    return {
        "schema.yaml": _OPENAI_SCHEMA_YAML,
        "tools.py": _TOOLS_PY,
        "handlers.py": _HANDLERS_PY,
        "routing.py": _ROUTING_PY,
        "NOTES.md": _NOTES_MD,
        ".env.example": env_example,
    }


def scaffold(dest: Path, provider: str, force: bool) -> list[Path]:
    """Write a starter project for PROVIDER into DEST, creating it if needed.

    Raises ScaffoldExistsError (and writes nothing) if any target file
    already exists and FORCE is False.
    """
    files = _files_for(provider)
    existing = sorted(name for name in files if (dest / name).exists())
    if existing and not force:
        raise ScaffoldExistsError(existing)

    dest.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, content in files.items():
        path = dest / name
        path.write_text(content)
        written.append(path)
    return written
